/**
 * Monol Rulebook - Cursor Adapter
 *
 * .cursorrules 파일 동기화 어댑터
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import type { Rule } from '../types.js';
import {
  BasePlatformAdapter,
  rulesToDirectives,
  rulesToMarkdownDocument,
  registerAdapter,
} from './platform-adapter.js';

// ============================================================================
// Cursor Adapter
// ============================================================================

export class CursorAdapter extends BasePlatformAdapter {
  name = 'cursor';
  private outputFile = '.cursorrules';

  protected getOutputPath(): string {
    return path.join(this.basePath, this.outputFile);
  }

  async read(): Promise<string> {
    try {
      return await fs.readFile(this.getOutputPath(), 'utf-8');
    } catch {
      return '';
    }
  }

  format(rules: Rule[]): string {
    // Cursor에서 활성화된 규칙만 필터링
    const cursorRules = rules.filter(r =>
      r.enabled !== false &&
      (r.platforms?.cursor?.enabled !== false || !r.platforms)
    );

    // 포함 여부 필터링
    const includeRules = cursorRules.filter(r =>
      r.platforms?.cursor?.includeInRules !== false
    );

    const lines: string[] = [];

    // 헤더
    lines.push('# Project Rules');
    lines.push('');
    lines.push('> Auto-generated by Monol Rulebook');
    lines.push(`> Last updated: ${new Date().toISOString()}`);
    lines.push('');

    // 규칙 요약
    lines.push('## Overview');
    lines.push('');
    lines.push(`Total rules: ${includeRules.length}`);
    lines.push('');

    // 카테고리별 그룹화
    const byCategory = new Map<string, Rule[]>();
    for (const rule of includeRules) {
      const category = rule.category.split('/')[0];
      if (!byCategory.has(category)) {
        byCategory.set(category, []);
      }
      byCategory.get(category)!.push(rule);
    }

    // 규칙 출력
    for (const [category, catRules] of byCategory) {
      lines.push(`## ${this.capitalizeFirst(category)} Rules`);
      lines.push('');

      for (const rule of catRules) {
        lines.push(this.formatRule(rule));
        lines.push('');
      }
    }

    // 푸터
    lines.push('---');
    lines.push('');
    lines.push('For more details, run `/rule <id>` in Claude Code');

    return lines.join('\n');
  }

  async write(content: string): Promise<void> {
    await this.ensureDir(this.getOutputPath());
    await fs.writeFile(this.getOutputPath(), content, 'utf-8');
  }

  private formatRule(rule: Rule): string {
    const lines: string[] = [];

    // 규칙 헤더
    const severityEmoji = rule.severity === 'error' ? '🔴' :
                          rule.severity === 'warning' ? '🟡' : '🔵';
    lines.push(`### ${severityEmoji} ${rule.name}`);
    lines.push('');

    // 설명
    lines.push(rule.description.trim());
    lines.push('');

    // 예시
    if (rule.examples) {
      if (rule.examples.good && rule.examples.good.length > 0) {
        lines.push('**Do:**');
        lines.push('```');
        for (const example of rule.examples.good) {
          lines.push(example.trim());
        }
        lines.push('```');
        lines.push('');
      }

      if (rule.examples.bad && rule.examples.bad.length > 0) {
        lines.push("**Don't:**");
        lines.push('```');
        for (const example of rule.examples.bad) {
          lines.push(example.trim());
        }
        lines.push('```');
        lines.push('');
      }
    }

    // 예외
    if (rule.exceptions && rule.exceptions.length > 0) {
      lines.push('**Exceptions:**');
      for (const exception of rule.exceptions) {
        lines.push(`- ${exception}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  private capitalizeFirst(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

// 어댑터 등록
registerAdapter('cursor', CursorAdapter);

export default CursorAdapter;
